version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flexstaff-postgres
    environment:
      POSTGRES_DB: flexstaff_db
      POSTGRES_USER: flexstaff_user
      POSTGRES_PASSWORD: flexstaff_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flexstaff-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flexstaff_user -d flexstaff_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flexstaff-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - flexstaff-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: flexstaff-backend
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://flexstaff_user:flexstaff_pass@postgres:5432/flexstaff_db
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: flexstaff_db
      DB_USER: flexstaff_user
      DB_PASSWORD: flexstaff_pass
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-secret-key-change-in-production
      JWT_REFRESH_SECRET: your-refresh-secret-change-in-production
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - flexstaff-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: flexstaff-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - flexstaff-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    container_name: flexstaff-admin
    ports:
      - "5174:5174"
    environment:
      VITE_API_URL: http://localhost:4000
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - flexstaff-network

volumes:
  postgres_data:
  redis_data:

networks:
  flexstaff-network:
    driver: bridge
